In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
Data_path = "/content/drive/MyDrive/Shreyas Shared Folder/AI Learning/house_prices_processed.csv"

In [ ]:
import pandas as pd
df = pd.read_csv(Data_path)
df.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,False,False,False,False,False,True,False,False,False,True
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,False,False,False,False,False,True,False,False,False,True
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,False,False,False,False,False,True,False,False,False,True
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,False,False,False,False,False,True,False,False,False,False
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,False,False,False,False,False,True,False,False,False,True

In [ ]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=0.2) # train 80%, test 20%
test, validation = train_test_split(test, test_size=0.5) #test 10%, validation 10%

train.to_csv("/content/drive/MyDrive/Shreyas Shared Folder/AI Learning/train_processed.csv", index=False)
test.to_csv("/content/drive/MyDrive/Shreyas Shared Folder/AI Learning/test_processed.csv", index=False)
validation.to_csv("/content/drive/MyDrive/Shreyas Shared Folder/AI Learning/validation_processed.csv", index=False)

In [ ]:
train = pd.read_csv("/content/drive/MyDrive/Shreyas Shared Folder/AI Learning/train_processed.csv")
validation = pd.read_csv("/content/drive/MyDrive/Shreyas Shared Folder/AI Learning/validation_processed.csv")

In [ ]:
train_features = train.drop('SalePrice', axis=1)
train_label = train['SalePrice']

In [ ]:
# import linear regression model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(train_features, train_label)

LinearRegression()

In [ ]:
features_val = validation.drop('SalePrice', axis=1)
label_val = validation['SalePrice']

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
def evaluate_model(model, features, labels):
  # Predict on test set
  y_pred = model.predict(features_val)

  # Calculate MAE
  mae = mean_absolute_error(label_val, y_pred)

  # Calculate RMSE
  rmse = np.sqrt(mean_squared_error(label_val, y_pred))

  # Calculate MAPE
  mape = np.mean(np.abs((label_val - y_pred) / label_val)) * 100

  # Print the results
  print(f"MAE: {mae:.4f}")
  print(f"RMSE: {rmse:.4f}")
  print(f"MAPE: {mape:.2f}%")

In [ ]:
train_label.describe()

count      1161.000000
mean     179368.589147
std       76889.020311
min       34900.000000
25%      130000.000000
50%      161000.000000
75%      213250.000000
max      755000.000000
Name: SalePrice, dtype: float64

##SVR

In [ ]:
from sklearn.svm import SVR
model = SVR(kernel='poly', degree=3)
model.fit(train_features, train_label)
evaluate_model(model, features_val, label_val)

MAE: 58275.6736
RMSE: 85689.9373
MAPE: 31.16%