## Air processing

In [ ]:
import json
import pandas as pd

# change the below according to the sample
specimen_file_path = "/content/air_1.bmespecimen"
label = "air"

with open(specimen_file_path, 'r') as f:
    data = json.load(f)

sensor_data = data.get('data')
specimenDataPoints = sensor_data.get('specimenDataPoints')
if specimenDataPoints:
    print("Extracted specimenDataPoints:")
    print(specimenDataPoints)
        # Separate the IDs and data
    ids = [point[0] for point in specimenDataPoints]
    data_values = [point[1:] for point in specimenDataPoints]

    # Create the DataFrame
    df = pd.DataFrame(data_values)

    # Insert the ID column at the beginning
    df.insert(0, 'id', ids)

    print("DataFrame created:")
    display(df.head())
else:
    print("'specimenDataPoints' key not found in the JSON data.")

# getting sensor values for each step in the cycles
dataset = {}
for i in range(0,10):
  filtered_list = df.loc[df[7] == i, 0].tolist()
  dataset[str(i)] = filtered_list
print(dataset)

# convert extracted values to a dataframe
min_len = min(len(v) for v in dataset.values())
for k, v in dataset.items():
    dataset[k] = v[:min_len]
df = pd.DataFrame(dataset)
# df.head()

# Add data label
df['label'] = label
df.head()

# Save the data
df.to_csv(f"{label}.csv", index = False)

Extracted specimenDataPoints:

,id,0,1,2,3,4,5,6,7,8
0,51,10145.846680,26.747105,1003.963623,55.978783,0,1763826106,0,0,6
1,52,163578.281250,26.627234,1004.038391,55.423664,280,1763826106,0,1,6
2,53,166938.375000,26.856770,1004.055420,52.528095,1680,1763826108,0,2,6
3,54,164683.171875,27.221476,1004.046143,46.133724,5880,1763826112,0,3,6
4,55,34427.113281,27.754511,1004.070984,45.520061,6580,1763826113,0,4,6

{'0': [10145.84668, 50723.203125, 88123.921875, 118408.882812, 141592.921875, 75360.609375, 148491.875, 178086.953125, 202892.8125, 219178.078125, 103727.710938, 197378.5625, 228877.96875, 246390.765625, 259898.484375, 117674.101562, 224364.59375, 256770.3125, 273650.46875, 285794.03125, 124908.515625, 241680.4375, 272993.875, 289920.71875, 299853.59375, 130645.570312, 253152.046875, 287721.28125, 302779.40625, 313341.5, 133716.375, 260493.515625, 295953.75, 311340.84375, 324976.1875, 135306.546875, 268273.5, 303857.5625, 321003.125, 331606.21875, 138266.265625, 272557.90625, 306037.0625, 322824.71875, 335847.8125, 139281.828125, 274089.9375, 312195.125, 330003.21875, 339185.15625, 140543.515625, 278791.1875, 313341.5, 332899.875, 341561.03125, 139395.59375, 279705.0, 318308.96875, 340199.34375, 346062.84375, 140082.078125, 282951.09375, 319500.78125, 338512.40625, 349249.65625, 12539.18457, 75896.828125, 131450.578125, 169592.578125, 204106.046875, 102359.054688, 210396.546875, 251473.484375, 274751.8125, 293409.75, 130246.757812, 260294.859375, 297242.375, 317716.40625, 330003.21875, 142420.03125, 283185.84375, 324358.5625, 339522.53125, 351407.0, 148362.796875, 299853.59375, 335847.8125, 353957.84375, 365714.28125, 151928.78125, 305216.09375, 345362.5625, 365322.875, 380457.0, 154402.890625, 314206.8125, 354693.46875, 376055.8125, 386488.03125, 154542.703125, 319202.0, 354325.25, 384096.03125, 390020.9375, 156240.46875, 321911.34375, 361454.28125, 386050.90625, 395443.125, 156958.921875, 323436.5, 363765.53125, 388246.4375, 396591.78125, 157103.40625, 325596.1875, 362991.84375, 388910.0, 397979.0, 157538.46875, 327784.90625, 376470.59375, 394073.5, 402674.0, 157684.015625, 329366.34375, 366106.53125, 392487.53125, 403865.125, 27520.962891, 119990.625, 183842.015625, 234862.390625, 266181.4375, 160804.015625, 267432.75, 305762.90625, 323130.3125, 335517.6875, 197378.5625, 303587.3125, 342589.5, 358041.96875, 369275.15625, 211439.1875, 327470.40625, 357666.78125, 380245.09375, 389575.8125, 217779.671875, 336178.59375, 369675.09375, 389798.25, 402199.53125, 226148.40625, 347118.65625, 383233.53125, 400547.625, 406752.71875, 228418.46875, 349249.65625, 387145.5625, 405303.78125, 414658.84375, 230112.359375, 353591.15625, 391362.5, 410174.25, 418471.59375, 233098.109375, 358041.96875, 395901.8125, 413904.59375, 421052.625, 234378.578125, 359172.21875, 399142.46875, 415415.8125, 423665.6875, 234217.75, 360309.65625, 401726.15625, 418728.28125, 426045.34375, 234539.625, 365714.28125, 403387.8125, 420016.40625, 427378.96875, 235673.1875, 363378.28125, 405303.78125, 420275.0, 430342.5, 13742.75293, 74440.242188, 127617.148438, 167101.828125, 200156.375, 105328.125, 207077.859375, 243925.671875, 271906.53125, 287237.03125, 134031.40625, 254094.296875, 288207.15625, 307969.9375, 322519.6875, 146327.515625, 275416.90625, 312480.9375, 330322.59375, 339522.53125, 151658.765625, 289183.84375, 327156.5625, 341561.03125, 351045.59375, 156670.75, 298803.625, 338177.0, 352495.6875, 364542.53125, 158858.203125, 304128.3125, 342246.0, 360309.65625, 371283.53125, 160050.015625, 308805.78125, 346062.84375, 366106.53125, 380033.40625, 161565.15625, 309927.375, 350684.9375, 370880.125, 383664.28125, 162025.3125, 313054.125, 353225.25, 369675.09375, 384745.4375, 162488.09375, 314206.8125, 353957.84375, 377511.53125, 385832.71875, 162488.09375, 316537.875, 361454.28125, 378348.40625, 385397.0625, 162488.09375, 315951.875, 359550.5625, 380457.0, 392262.03125, 8228.335938, 54549.328125, 100254.554688, 138378.375, 166449.9375, 77622.804688, 175703.5, 218197.3125, 243403.84375, 260692.46875, 104682.070312, 232146.90625, 270184.6875, 292906.1875, 307415.1875, 114362.296875, 258520.578125, 299065.40625, 314206.8125, 326530.625, 119654.125, 274530.84375, 313054.125, 333224.875, 346062.84375, 123106.515625, 286273.40625, 326530.625, 343278.59375, 358041.96875, 125091.617188, 292655.03125, 336510.03125, 350325.0, 366499.65625, 126669.96875, 298281.375, 340199.34375, 359172.21875, 367684.03125, 128096.070312, 301975.8125, 343970.4375, 363378.28125, 383018.5, 128481.804688, 306037.0625, 349965.8125, 375435.375, 384312.25, 128772.632812, 309085.40625, 353225.25, 378558.21875, 386926.125, 128772.632812, 310773.90625, 354693.46875, 379189.03125, 390914.28125, 129456.382812, 310491.21875, 355432.15625, 382374.90625, 392713.3125, 6118.546875, 47743.378906, 89982.421875, 127521.796875, 156958.921875, 72851.453125, 169424.21875, 211701.46875, 235510.578125, 251844.5625, 97616.78125, 225699.796875, 260692.46875, 282716.71875, 293157.75, 107180.242188, 250734.578125, 287237.03125, 302779.40625, 312767.25, 109659.453125, 263306.75, 302243.21875, 317126.03125, 329048.84375, 112700.859375, 271258.28125, 311909.84375, 326530.625, 339185.15625, 113828.367188, 279475.96875, 319800.125, 334531.1875, 347118.65625, 114746.75, 281550.71875, 323743.28125, 339860.59375, 348892.6875, 115601.71875, 285316.25, 327470.40625, 344665.09375, 356173.90625, 115601.71875, 289920.71875, 328415.65625, 347472.0, 360690.375, 115758.53125, 289183.84375, 330642.5625, 351769.15625, 363765.53125, 117189.289062, 291654.8125, 333224.875, 355062.40625, 368080.53125, 116073.453125, 292404.34375, 335847.8125, 351407.0, 367288.375, 5684.846191, 28705.988281, 62317.429688, 90363.570312, 111741.59375, 57257.882812, 122488.039062, 145827.40625, 158710.484375, 166938.375, 71388.734375, 152335.609375, 173559.328125, 183842.015625, 194676.8125, 75493.953125, 165642.1875, 184438.046875, 199454.609375, 203497.609375, 75627.773438, 171466.84375, 196018.375, 205333.875, 210266.9375, 75493.953125, 175703.5, 200039.0625, 209235.796875, 217363.609375, 75029.304688, 177716.078125, 204106.046875, 214495.1875, 220025.78125, 74963.398438, 178833.390625, 206952.296875, 216536.265625, 222463.609375, 74310.59375, 179775.28125, 207581.59375, 217087.125, 223629.609375, 73101.085938, 179775.28125, 207961.0, 217779.671875, 224512.171875, 72603.515625, 179775.28125, 208087.78125, 218336.890625, 226598.8125, 71688.601562, 180345.1875, 208596.453125, 221309.703125, 224807.90625, 71628.429688, 179964.84375, 208596.453125, 218616.5625, 225699.796875, 5684.846191, 26090.501953, 54724.242188, 80100.125, 101567.148438, 46159.394531, 114132.859375, 138490.671875, 154263.328125, 167101.828125, 65877.507812, 150854.453125, 172681.28125, 185238.78125, 199804.875, 71388.734375, 168421.046875, 195457.140625, 206952.296875, 213823.34375, 74116.96875, 176795.578125, 205087.125, 216124.953125, 225252.96875, 75964.390625, 183249.828125, 212096.109375, 227505.0, 232463.109375, 76032.078125, 191080.421875, 217502.125, 226448.46875, 235348.203125, 77062.007812, 194899.125, 221023.09375, 231674.203125, 237476.8125, 76784.640625, 196469.6875, 224956.0625, 239308.25, 244624.9375, 76715.609375, 198642.09375, 226298.34375, 236653.578125, 242711.546875, 76099.882812, 197378.5625, 225550.65625, 237311.703125, 246925.484375, 76372.3125, 199687.984375, 228265.71875, 243057.203125, 247821.875, 75762.0625, 199221.796875, 228418.46875, 241680.4375, 251844.5625], '1': [163578.28125, 1656622.875, 3561739.25, 5342028.0, 7222393.5, 3550162.5, 7953398.0, 10320630.0, 12523600.0, 14463915.0, 6279800.5, 13141368.0, 16141872.0, 18169116.0, 20035464.0, 8053084.5, 17088918.0, 20660782.0, 22795130.0, 25047200.0, 9153073.0, 20239654.0, 24349248.0, 26667752.0, 28493914.0, 9990244.0, 22842802.0, 27335140.0, 29674440.0, 31515268.0, 10560103.0, 25061568.0, 29514074.0, 32023454.0, 33833764.0, 11007054.0, 26635236.0, 31155692.0, 34097816.0, 35831600.0, 11373829.0, 28145158.0, 33115716.0, 35743660.0, 37621124.0, 11690332.0, 29062528.0, 34285116.0, 37427756.0, 39207896.0, 11894011.0, 30041714.0, 35569064.0, 38516604.0, 40181484.0, 12195013.0, 30847728.0, 36984200.0, 39815308.0, 41716104.0, 12291073.0, 31424598.0, 37556448.0, 40441840.0, 42569664.0, 261491.3125, 4710753.5, 11778577.0, 19446884.0, 26914168.0, 8957900.0, 28346020.0, 38652904.0, 46413596.0, 53400692.0, 14331074.0, 42736224.0, 55574304.0, 63121600.0, 68462784.0, 17156020.0, 52628788.0, 64329816.0, 71254144.0, 75567600.0, 18445258.0, 57740968.0, 70223416.0, 76695144.0, 80734216.0, 19481570.0, 60249140.0, 74031064.0, 80883680.0, 83671880.0, 19962230.0, 63030536.0, 76426824.0, 83352624.0, 87352216.0, 20296066.0, 64806924.0, 79197584.0, 84644496.0, 89867672.0, 20467208.0, 66281668.0, 79703256.0, 87527216.0, 92142000.0, 20958106.0, 67302696.0, 81639368.0, 88952832.0, 92728688.0, 20680340.0, 67825096.0, 83114776.0, 89867672.0, 93522656.0, 20778694.0, 68516464.0, 82878280.0, 91371208.0, 94842256.0, 20798476.0, 68786144.0, 84155376.0, 91371208.0, 95359768.0, 954556.0625, 9324986.0, 19998780.0, 30652946.0, 39527140.0, 18924632.0, 41517896.0, 53994644.0, 61739048.0, 68786144.0, 28908690.0, 59673116.0, 70792328.0, 78769232.0, 83832424.0, 33807584.0, 68516464.0, 80289128.0, 88056432.0, 92925912.0, 36520480.0, 73781032.0, 87091032.0, 93723272.0, 99485392.0, 38652904.0, 77787536.0, 92532296.0, 99712440.0, 102400000.0, 39888008.0, 81639368.0, 95568352.0, 102400000.0, 102400000.0, 40516848.0, 83671880.0, 98254872.0, 102400000.0, 102400000.0, 41282520.0, 85056456.0, 99598784.0, 102400000.0, 102400000.0, 41876040.0, 87091032.0, 101922240.0, 102400000.0, 102400000.0, 42118252.0, 87439624.0, 102400000.0, 102400000.0, 102400000.0, 42486872.0, 87439624.0, 102400000.0, 102400000.0, 102400000.0, 42736224.0, 89225320.0, 102400000.0, 102400000.0, 102400000.0, 265353.71875, 3770771.0, 9214848.0, 14609006.0, 19710076.0, 7625785.5, 20978234.0, 28181466.0, 33165992.0, 36890516.0, 11816805.0, 30609996.0, 38790176.0, 43588960.0, 46962380.0, 14018396.0, 36766340.0, 44703956.0, 51000780.0, 54533804.0, 15262226.0, 40255528.0, 50412308.0, 54807444.0, 57932376.0, 15941620.0, 43158380.0, 53729044.0, 57970808.0, 61521708.0, 16520292.0, 44567156.0, 55538984.0, 59918628.0, 63534660.0, 16851632.0, 45733428.0, 56876544.0, 61521708.0, 64806924.0, 17223654.0, 47472656.0, 58086416.0, 63167228.0, 66181268.0, 17332980.0, 47679884.0, 59028148.0, 63813048.0, 67095980.0, 17415892.0, 49109028.0, 59632392.0, 64806924.0, 67354576.0, 17443706.0, 50037028.0, 60207624.0, 65145128.0, 68570232.0, 17443706.0, 49639084.0, 61305892.0, 65486884.0, 69276952.0, 116390.085938, 2271139.5, 6159398.5, 10448980.0, 14918279.0, 4714820.0, 16722633.0, 23011236.0, 28549772.0, 32718922.0, 7901615.5, 27663994.0, 35831600.0, 40781580.0, 44431188.0, 9317032.0, 33859984.0, 42819992.0, 49191968.0, 52345048.0, 10262449.0, 38180016.0, 47731972.0, 54128432.0, 58086416.0, 10832397.0, 41636596.0, 53238016.0, 58086416.0, 61651928.0, 11245024.0, 42611184.0, 55014480.0, 60921216.0, 64710936.0, 11529909.0, 45212832.0, 58125056.0, 64000000.0, 67044500.0, 11727989.0, 46315196.0, 59959744.0, 64758892.0, 68894616.0, 11791292.0, 47576044.0, 61048904.0, 67406528.0, 70167024.0, 11868164.0, 47731972.0, 61695456.0, 68355672.0, 70907224.0, 12188209.0, 50151904.0, 63121600.0, 69552664.0, 72255792.0, 11946044.0, 50267304.0, 63121600.0, 69331920.0, 73040960.0, 72913.703125, 1986902.75, 5686914.5, 10166925.0, 14677716.0, 4232498.0, 17156020.0, 24214298.0, 29474252.0, 33065590.0, 7045366.5, 27929256.0, 35453612.0, 40070928.0, 43201056.0, 8367722.0, 33015618.0, 41557388.0, 46168368.0, 50354208.0, 8863403.0, 36735428.0, 46168368.0, 51786644.0, 54262884.0, 9238229.0, 39278392.0, 50470544.0, 55716048.0, 58280124.0, 9454126.0, 40857856.0, 52219920.0, 57893992.0, 61177128.0, 9654685.0, 42363284.0, 54330364.0, 60207624.0, 62849196.0, 9784413.0, 42652784.0, 55609672.0, 61262912.0, 64424676.0, 9837286.0, 43415700.0, 55645084.0, 63304516.0, 65486884.0, 9714794.0, 44028216.0, 57702840.0, 62668896.0, 65782684.0, 9766915.0, 44567156.0, 59228196.0, 63304516.0, 67354576.0, 9706161.0, 44795624.0, 58319020.0, 64710936.0, 67615168.0, 22168.341797, 1213270.125, 4248962.5, 7970810.0, 11338408.0, 3666965.0, 13228906.0, 18199390.0, 21600528.0, 24513184.0, 5570894.5, 20202220.0, 25755944.0, 28549772.0, 30588564.0, 6135180.5, 23330722.0, 29594040.0, 32212338.0, 33343170.0, 6349157.0, 25545118.0, 31515268.0, 34528976.0, 36338232.0, 6412524.5, 27014014.0, 33216422.0, 35979140.0, 37686028.0, 6356547.0, 27080992.0, 34583640.0, 37015532.0, 38415004.0, 6345468.5, 28327642.0, 35224940.0, 38080184.0, 40070928.0, 6294276.0, 28217868.0, 35714440.0, 38997916.0, 40329848.0, 6258212.5, 28456796.0, 35890472.0, 38963140.0, 40819684.0, 6100912.5, 28870484.0, 36068244.0, 39207896.0, 40857856.0, 6073772.0, 28475342.0, 36217740.0, 39706756.0, 41011264.0, 5870297.5, 28851420.0, 35979140.0, 39742876.0, 41399872.0, 25574.425781, 841067.75, 2457108.5, 4475280.0, 6461842.0, 2228509.25, 7636448.5, 10438993.0, 13000595.0, 15020857.0, 4142604.25, 13228906.0, 17102296.0, 19586372.0, 21079446.0, 4986001.0, 17223654.0, 21368112.0, 23355666.0, 25545118.0, 5437769.5, 20127764.0, 24693294.0, 27283930.0, 29120640.0, 5716678.5, 21794480.0, 27300978.0, 28927830.0, 31447216.0, 5845166.0, 23430818.0, 29043208.0, 31606462.0, 33419684.0, 6023529.5, 24961340.0, 30739212.0, 33368636.0, 34339008.0, 6131736.5, 25620016.0, 31767330.0, 34339008.0, 36338232.0, 6100912.5, 26282736.0, 32000000.0, 34887412.0, 37078360.0, 6067024.5, 26538166.0, 32694438.0, 35598044.0, 37783800.0, 6121427.0, 26914168.0, 33216422.0, 36797304.0, 38013920.0, 6073772.0, 27097788.0, 34447308.0, 36797304.0, 38928424.0], '2': [166938.375, 1605015.625, 3427615.0, 5121600.5, 6816725.5, 3362200.0, 7505268.0, 9793186.0, 11591086.0, 13490325.0, 5710700.5, 12208644.0, 14908098.0, 16773995.0, 18618182.0, 7246351.0, 15655996.0, 18665908.0, 20838156.0, 22583046.0, 8222835.5, 18184240.0, 21664794.0, 24241168.0, 25665166.0, 8943231.0, 20409842.0, 24444610.0, 26782182.0, 28438272.0, 9503480.0, 22103204.0, 26619008.0, 28870484.0, 30567164.0, 9890733.0, 23531778.0, 27965010.0, 30869524.0, 32403462.0, 10157471.0, 24918632.0, 29296380.0, 32307616.0, 33991700.0, 10349968.0, 25725614.0, 30739212.0, 33165992.0, 35338904.0, 10570323.0, 26489894.0, 31402012.0, 34474488.0, 36157792.0, 10704998.0, 27300978.0, 32596866.0, 35168232.0, 37204656.0, 10810953.0, 27875798.0, 33703264.0, 36187740.0, 37783800.0, 253152.046875, 4235781.0, 10291457.0, 16735444.0, 22747658.0, 7856149.5, 24349248.0, 32499876.0, 38146684.0, 43073284.0, 12201825.0, 36157792.0, 44703956.0, 51603148.0, 56181740.0, 14658018.0, 42778068.0, 53663052.0, 59754728.0, 62489632.0, 15678469.0, 46761328.0, 58163744.0, 63719980.0, 66993100.0, 16371721.0, 50971028.0, 61782700.0, 67147544.0, 69886432.0, 17022338.0, 52470776.0, 64093888.0, 69222072.0, 72858256.0, 17223654.0, 54028028.0, 65388876.0, 70563664.0, 74536256.0, 17223654.0, 55787188.0, 69442120.0, 72797560.0, 76360032.0, 17584116.0, 56362932.0, 68516464.0, 73905832.0, 76226808.0, 17555854.0, 56913592.0, 69112576.0, 74219704.0, 77305808.0, 17598282.0, 57550824.0, 69942368.0, 75307096.0, 78415792.0, 17915800.0, 57893992.0, 70449880.0, 75961752.0, 79125864.0, 926068.25, 8806235.0, 18586500.0, 28036792.0, 35890472.0, 17250856.0, 37046920.0, 47318412.0, 55363040.0, 60963720.0, 25832086.0, 52033348.0, 62311384.0, 69331920.0, 74791440.0, 29816196.0, 60457564.0, 70792328.0, 76627888.0, 81335400.0, 32259906.0, 65536000.0, 76293368.0, 83035792.0, 85724000.0, 34177836.0, 68570232.0, 80734216.0, 87177920.0, 90425664.0, 35367512.0, 71080264.0, 82878280.0, 88772096.0, 94025824.0, 36308032.0, 72315584.0, 85639984.0, 93223328.0, 97054424.0, 36704564.0, 74919688.0, 87177920.0, 94739432.0, 98365480.0, 37173000.0, 75633008.0, 88323448.0, 95882952.0, 99712440.0, 37363740.0, 76493728.0, 89499488.0, 96199632.0, 101448920.0, 37980876.0, 76897624.0, 91562696.0, 98254872.0, 101566832.0, 38180016.0, 78415792.0, 92532296.0, 98922264.0, 102400000.0, 263510.03125, 3486699.25, 8222835.5, 12855237.0, 17388166.0, 6902886.0, 18123894.0, 24582146.0, 29004648.0, 32259906.0, 10438993.0, 26667752.0, 33267006.0, 37204656.0, 40181484.0, 12438034.0, 31652258.0, 38246864.0, 42404400.0, 44612660.0, 13407529.0, 34528976.0, 41596952.0, 46217208.0, 49136644.0, 14054471.0, 36859392.0, 44117132.0, 48971416.0, 51451228.0, 14359334.0, 38280372.0, 46811428.0, 50793256.0, 53795200.0, 14717269.0, 38963140.0, 47524292.0, 52660508.0, 55292976.0, 14857402.0, 40181484.0, 49695544.0, 53564364.0, 56472212.0, 15166860.0, 40479308.0, 50065700.0, 54364164.0, 56913592.0, 15337234.0, 40896100.0, 50587416.0, 56001708.0, 57550824.0, 15166860.0, 41517896.0, 51633640.0, 55751596.0, 58750336.0, 15272897.0, 41795920.0, 51940560.0, 56399312.0, 58592760.0, 118821.070312, 1978266.125, 5097697.5, 8551148.0, 11868164.0, 3985405.0, 13432261.0, 18697860.0, 22653302.0, 25801574.0, 6477169.5, 21494260.0, 27769492.0, 31790444.0, 34971184.0, 7604548.5, 26538166.0, 33191188.0, 36952916.0, 39960976.0, 8235235.0, 29714804.0, 37299944.0, 41011264.0, 43763608.0, 8813341.0, 32023454.0, 40292652.0, 44251180.0, 46861636.0, 9122494.0, 33573772.0, 41636596.0, 46071000.0, 50296240.0, 9413387.0, 35055364.0, 43763608.0, 49582752.0, 52439288.0, 9646158.0, 36187740.0, 45353632.0, 50793256.0, 54431892.0, 9688941.0, 36859392.0, 46364344.0, 52157580.0, 54945296.0, 9688941.0, 38113404.0, 46711332.0, 53140888.0, 55716048.0, 9775656.0, 38047024.0, 47576044.0, 54028028.0, 56987828.0, 9837286.0, 38381260.0, 49780480.0, 54807444.0, 57136880.0, 75161.476562, 1594705.125, 4406670.5, 7761250.5, 10853925.0, 3366344.75, 12742757.0, 17584116.0, 21284832.0, 24458294.0, 5437769.5, 20258424.0, 26346130.0, 29755278.0, 31953194.0, 6558847.0, 24349248.0, 31089184.0, 34556288.0, 37173000.0, 6929160.5, 27455384.0, 34393072.0, 37914956.0, 39742876.0, 7165537.0, 28889574.0, 37459844.0, 40218472.0, 42322248.0, 7464237.0, 30609996.0, 38213412.0, 41835940.0, 43851456.0, 7641791.0, 31652258.0, 39815308.0, 43763608.0, 45925720.0, 7816794.0, 32427512.0, 40516848.0, 44567156.0, 47063556.0, 7844864.5, 33040584.0, 41636596.0, 45353632.0, 47784176.0, 7766769.5, 33140834.0, 42158892.0, 46071000.0, 47836496.0, 7867467.0, 34018168.0, 42946264.0, 46661444.0, 50209540.0, 7794481.5, 34231392.0, 43286656.0, 47369716.0, 51390708.0, 24141.833984, 914285.6875, 2954201.25, 5509078.5, 7867467.0, 2652849.75, 9130120.0, 12459316.0, 14677716.0, 16697070.0, 4059464.75, 14108934.0, 17555854.0, 19781466.0, 21079446.0, 4475280.0, 16470470.0, 20258424.0, 22374872.0, 23231478.0, 4619114.5, 17915800.0, 22014108.0, 24349248.0, 25620016.0, 4718894.0, 18697860.0, 23133074.0, 25530190.0, 26815058.0, 4694556.0, 19207502.0, 24241168.0, 26235388.0, 27611544.0, 4764175.5, 20035464.0, 25381874.0, 27438142.0, 28870484.0, 4731158.0, 20183554.0, 25440994.0, 27822542.0, 29355432.0, 4714820.0, 20258424.0, 25924050.0, 28127038.0, 29276748.0, 4638731.5, 20467208.0, 26172524.0, 28475342.0, 29755278.0, 4623025.0, 20563540.0, 26441800.0, 29257142.0, 29938784.0, 4561247.0, 20877986.0, 26377944.0, 29198486.0, 30062386.0, 27344.583984, 702091.1875, 2038825.25, 3644938.75, 5300550.0, 1854652.5, 6356547.0, 8571279.0, 10489117.0, 12201825.0, 3299234.75, 10601100.0, 13676127.0, 15533539.0, 17048908.0, 3968031.0, 13684694.0, 16890722.0, 18810562.0, 20390790.0, 4312714.0, 15803231.0, 19224406.0, 21452046.0, 22818942.0, 4538504.0, 17291820.0, 21243436.0, 23084184.0, 24890240.0, 4630865.0, 18260240.0, 22629834.0, 24735234.0, 26219644.0, 4764175.5, 19258302.0, 24227726.0, 26346130.0, 27420920.0, 4853080.5, 19889530.0, 25018514.0, 27283930.0, 28401300.0, 4887828.0, 20390790.0, 25352418.0, 27663994.0, 28908690.0, 4844470.5, 20621774.0, 26109960.0, 28309288.0, 30124570.0, 4887828.0, 21059126.0, 26298556.0, 29237564.0, 30041714.0, 4879094.5, 21222798.0, 26864522.0, 29296380.0, 30825964.0], '3': [164683.171875, 1539849.625, 3232833.5, 4731158.0, 6312464.0, 3118386.0, 6894172.0, 8870601.0, 10469010.0, 11816805.0, 5069307.0, 10642416.0, 13031617.0, 14727191.0, 16118052.0, 6349157.0, 13515364.0, 16011727.0, 17726806.0, 19140186.0, 7095712.5, 15600095.0, 18507766.0, 20146326.0, 21452046.0, 7772296.0, 17237244.0, 20390790.0, 21969830.0, 23430818.0, 8094861.5, 18429696.0, 21859906.0, 24054322.0, 25293708.0, 8354921.0, 19446884.0, 23084184.0, 25220704.0, 26409832.0, 8524454.0, 20258424.0, 24308606.0, 263143

## Fennel seeds processing

In [ ]:
import json
import pandas as pd

# change the below according to the sample
specimen_file_path = "/content/fennel_seeds_2.bmespecimen"
label = "fennel_seeds"

with open(specimen_file_path, 'r') as f:
    data = json.load(f)

sensor_data = data.get('data')
specimenDataPoints = sensor_data.get('specimenDataPoints')
if specimenDataPoints:
    print("Extracted specimenDataPoints:")
    print(specimenDataPoints)
        # Separate the IDs and data
    ids = [point[0] for point in specimenDataPoints]
    data_values = [point[1:] for point in specimenDataPoints]

    # Create the DataFrame
    df = pd.DataFrame(data_values)

    # Insert the ID column at the beginning
    df.insert(0, 'id', ids)

    print("DataFrame created:")
    display(df.head())
else:
    print("'specimenDataPoints' key not found in the JSON data.")

# getting sensor values for each step in the cycles
dataset = {}
for i in range(0,10):
  filtered_list = df.loc[df[7] == i, 0].tolist()
  dataset[str(i)] = filtered_list
print(dataset)

# convert extracted values to a dataframe
min_len = min(len(v) for v in dataset.values())
for k, v in dataset.items():
    dataset[k] = v[:min_len]
df = pd.DataFrame(dataset)
# df.head()

# Add data label
df['label'] = label
df.head()

# Save the data
df.to_csv(f"{label}.csv", index = False)

Extracted specimenDataPoints:

,id,0,1,2,3,4,5,6,7,8
0,5261,1.210974e+05,33.253349,1004.489136,32.155109,2099689,1763828206,0,0,527
1,5262,9.646158e+06,33.255901,1004.536865,31.976303,2099969,1763828206,0,1,527
2,5263,7.562428e+06,33.153881,1004.508484,30.977283,2101378,1763828208,0,2,527
3,5264,4.918643e+06,33.457397,1004.522095,29.010771,2105586,1763828212,0,3,527
4,5265,3.467660e+05,34.156254,1004.501831,28.828503,2106286,1763828213,0,4,527

{'0': [121097.445312, 223045.09375, 234217.75, 243057.203125, 250366.75, 94482.375, 201099.765625, 220737.234375, 224956.0625, 237311.703125, 94117.648438, 197378.5625, 221023.09375, 226749.328125, 225401.71875, 91624.914062, 195121.953125, 216536.265625, 228418.46875, 233576.640625, 95273.539062, 194012.890625, 210916.578125, 220880.0625, 229802.515625, 96458.179688, 196582.84375, 216124.953125, 221166.3125, 221741.015625, 95540.210938, 193134.671875, 212757.109375, 221741.015625, 227505.0, 97560.976562, 192698.53125, 212757.109375, 222463.609375, 227202.125, 97672.640625, 186249.546875, 208851.71875, 219884.046875, 225401.71875, 98404.765625, 194455.0, 211832.84375, 216124.953125, 217640.8125, 97227.5, 187066.125, 207834.375, 215851.609375, 220309.8125, 98803.546875, 195345.28125, 213823.34375, 209235.796875, 237973.5, 103101.085938, 211046.984375, 233416.90625, 243751.484375, 251473.484375, 109448.484375, 218756.671875, 242023.15625, 250734.578125, 258324.921875, 111376.984375, 224512.171875, 246746.984375, 257157.203125, 261691.796875, 113149.171875, 228418.46875, 250183.234375, 260692.46875, 267642.4375, 114285.710938, 232146.90625, 254853.15625, 264736.3125, 267642.4375, 115680.070312, 234862.390625, 257934.515625, 266181.4375, 271474.03125, 117189.289062, 238472.28125, 261291.140625, 267642.4375, 274310.21875, 117999.539062, 240997.875, 264121.75, 273212.375, 275416.90625, 119738.070312, 242539.078125, 265560.15625, 275194.84375, 280394.3125, 119570.296875, 244624.9375, 266181.4375, 276981.34375, 279934.375, 120244.25, 245858.34375, 271474.03125, 276981.34375, 282249.1875, 120925.835938, 248906.171875, 271042.875, 281318.6875, 285554.9375, 132368.15625, 241680.4375, 249634.328125, 257739.75, 266181.4375, 102914.570312, 220452.09375, 235673.1875, 241509.4375, 250366.75, 102543.5625, 216673.71875, 239308.25, 242711.546875, 239308.25, 102053.023438, 213689.484375, 233576.640625, 243577.546875, 249451.890625, 102605.210938, 209107.609375, 226598.8125, 235836.015625, 242711.546875, 104425.859375, 214630.0625, 234378.578125, 237476.8125, 234378.578125, 102666.9375, 210266.9375, 229031.53125, 236325.875, 242366.859375, 105263.15625, 210916.578125, 227202.125, 235999.078125, 240150.09375, 105588.78125, 207834.375, 224070.015625, 234539.625, 239812.640625, 105982.195312, 210396.546875, 227202.125, 231989.125, 232780.171875, 104298.226562, 207961.0, 222318.71875, 229802.515625, 234057.140625, 105850.734375, 210916.578125, 227960.8125, 229185.3125, 252777.09375, 112329.96875, 237311.703125, 256577.296875, 265974.03125, 273870.03125, 118821.070312, 243577.546875, 263306.75, 272775.71875, 277657.28125, 118986.75, 250550.53125, 272557.90625, 279705.0, 284128.75, 120754.71875, 255808.140625, 272557.90625, 282015.96875, 286995.53125, 121701.921875, 255808.140625, 276981.34375, 284365.46875, 288939.0625, 124362.398438, 259503.296875, 278791.1875, 285554.9375, 291654.8125, 124725.945312, 262698.8125, 283892.4375, 290909.09375, 292906.1875, 126015.257812, 262496.78125, 285794.03125, 290909.09375, 297760.96875, 126669.96875, 265353.71875, 286513.71875, 294422.09375, 299065.40625, 127331.507812, 265974.03125, 289674.6875, 295441.4375, 299327.6875, 127904.070312, 267642.4375, 288939.0625, 299590.40625, 301975.8125, 126952.640625, 268907.5625, 292655.03125, 300910.96875, 303857.5625, 202892.8125, 279705.0, 291157.25, 301975.8125, 307692.3125, 163421.640625, 274310.21875, 296210.59375, 300381.34375, 304128.3125, 165001.609375, 278336.5, 299590.40625, 301975.8125, 302243.21875, 166449.9375, 275862.0625, 298020.96875, 309085.40625, 312195.125, 167758.84375, 276981.34375, 297242.375, 306862.4375, 310209.03125, 170439.421875, 282249.1875, 300910.96875, 309365.5625, 310491.21875, 169256.203125, 278336.5, 300117.21875, 309927.375, 315659.6875, 173383.0, 280164.15625, 297242.375, 309927.375, 318012.4375, 174090.453125, 281087.03125, 296983.75, 307415.1875, 315951.875, 176247.84375, 283656.5, 305489.25, 309085.40625, 311340.84375, 173736.0, 284365.46875, 299590.40625, 308526.65625, 315368.03125, 175162.5, 286273.40625, 307415.1875, 315368.03125, 311625.0625, 183053.265625, 305762.90625, 329366.34375, 340878.84375, 344665.09375, 195681.25, 313341.5, 336510.03125, 345013.46875, 350325.0, 202531.640625, 315659.6875, 343278.59375, 351769.15625, 356173.90625, 201574.796875, 323130.3125, 344665.09375, 355432.15625, 359172.21875, 203740.546875, 325285.90625, 348536.40625, 355802.65625, 360309.65625, 203497.609375, 326530.625, 350325.0, 358794.6875, 363378.28125, 204472.84375, 326530.625, 353225.25, 360690.375, 364542.53125, 206326.8125, 332251.78125, 354325.25, 361837.46875, 368477.875, 206576.5625, 330003.21875, 354693.46875, 364153.625, 367684.03125, 207077.859375, 332575.5, 355802.65625, 365322.875, 370075.90625, 208596.453125, 333224.875, 359550.5625, 368477.875, 369275.15625, 208979.59375, 332899.875, 360690.375, 369275.15625, 377720.40625, 134031.40625, 229339.3125, 246213.03125, 257351.09375, 264121.75, 111231.804688, 221309.703125, 241168.15625, 246568.75, 259109.3125, 112256.085938, 219884.046875, 243577.546875, 242884.25, 243230.40625, 111087.0, 218197.3125, 238639.015625, 250918.890625, 256770.3125, 113149.171875, 217087.125, 236982.1875, 246925.484375, 254283.578125, 115367.28125, 221885.15625, 239308.25, 244449.75, 247283.265625, 114746.75, 218616.5625, 238805.96875, 247821.875, 252964.421875, 116073.453125, 217087.125, 237311.703125, 248182.265625, 253905.28125, 117350.445312, 215171.25, 235836.015625, 246925.484375, 252403.25, 117593.015625, 221166.3125, 236162.359375, 241851.671875, 246390.765625, 116788.320312, 215851.609375, 234378.578125, 244449.75, 250366.75, 118081.179688, 221453.28125, 238139.53125, 254283.578125, 265353.71875, 124634.859375, 241680.4375, 263713.625, 275862.0625, 283420.96875, 132368.15625, 251473.484375, 272993.875, 279934.375, 290414.0625, 133298.625, 256192.140625, 277883.3125, 286033.53125, 293662.1875, 134878.8125, 260891.71875, 282951.09375, 290909.09375, 295697.375, 136715.625, 265147.59375, 285316.25, 294930.875, 298281.375, 137819.65625, 266181.4375, 287721.28125, 295185.9375, 300645.90625, 139054.859375, 270613.09375, 291157.25, 299065.40625, 304399.53125, 139395.59375, 271474.03125, 292655.03125, 302511.09375, 306862.4375, 140659.34375, 272557.90625, 296210.59375, 305216.09375, 310773.90625, 141946.21875, 273431.25, 297242.375, 304399.53125, 310209.03125, 142182.734375, 276085.1875, 298281.375, 306037.0625, 313917.84375, 143377.203125, 278109.71875, 299853.59375, 307969.9375, 317126.03125, 86428.085938, 124634.859375, 125091.617188, 123284.375, 127236.578125, 50039.09375, 105785.125, 115837.101562, 119570.296875, 119319.507812, 48920.3125, 104682.070312, 114362.296875, 118573.414062, 116788.320312, 48948.375, 104234.53125, 113752.5, 117674.101562, 121011.578125, 50156.738281, 104810.648438, 114669.65625, 118162.9375, 120244.25, 50753.371094, 106113.992188, 114209.234375, 118408.882812, 119738.070312, 51179.527344, 103853.953125, 112329.96875, 117836.59375, 119990.625, 52021.945312, 105523.492188, 114056.585938, 116390.085938, 118738.40625, 52244.898438, 105328.125, 112626.484375, 114978.664062, 117350.445312, 52244.898438, 104939.539062, 112700.859375, 115915.78125, 116788.320312, 52117.265625, 103790.796875, 111522.546875, 114056.585938, 114901.257812, 52373.160156, 103980.5, 111741.59375, 114669.65625, 119990.625, 64144.324219, 138042.59375, 148491.875, 153431.21875, 155528.546875, 70737.773438, 146077.03125, 156527.0625, 161107.609375, 162179.28125, 73101.085938, 150987.90625, 160955.671875, 162488.09375, 165001.609375, 74897.601562, 152744.625, 163578.28125, 166125.890625, 167923.90625, 76099.882812, 155104.515625, 165321.28125, 168089.296875, 169761.265625, 77552.257812, 157684.015625, 168255.015625, 171294.75, 172856.171875, 78769.234375, 160200.25, 170099.671875, 174090.453125, 174268.203125, 80477.835938, 162488.09375, 171812.078125, 175522.796875, 176612.625, 80859.125, 163735.203125, 173559.328125, 176612.625, 179586.109375, 82580.648438, 164842.234375, 176612.625, 178833.390625, 181882.765625, 82821.09375, 167265.59375, 178646.203125, 182076.8125, 182857.140625, 83961.953125, 169592.578125, 180727.140625, 183053.265625, 185238.78125, 55980.757812, 80477.835938, 81710.820312, 82821.09375, 83550.914062, 31411.042969, 69357.898438, 76099.882812, 78407.351562, 79651.523438, 31597.136719, 69414.320312, 75560.804688, 77764.273438, 78914.921875, 31832.876953, 68798.710938, 75227.742188, 77271.351562, 78987.96875, 32266.195312, 68743.289062, 74440.242188, 76577.921875, 76715.609375, 32241.814453, 68139.476562, 72851.453125, 74897.601562, 75360.609375, 32193.158203, 66649.3125, 71448.507812, 72541.796875, 73478.757812, 31952.072266, 65624.195312, 70041.039062, 72051.789062, 72541.796875, 31503.814453, 64289.300781, 68030.828125, 70041.039062, 70562.296875, 31067.960938, 62000.484375, 66858.1875, 67976.632812, 68357.8125, 30556.21875, 61112.4375, 64826.539062, 66286.898438, 65877.507812, 30082.255859, 58675.222656, 63147.507812, 64386.316406, 73352.4375, 45181.785156, 101446.40625, 109238.320312, 110870.507812, 111888.109375, 52405.324219, 109518.71875, 116152.453125, 117999.539062, 117999.539062, 54340.902344, 112999.335938, 118655.851562, 120075.046875, 121183.429688, 55615.902344, 114978.664062, 121615.203125, 121701.921875, 124000.96875, 57104.617188, 115994.5625, 122137.40625, 122929.171875, 125275.265625, 57918.550781, 117999.539062, 124453.085938, 127617.148438, 127426.578125, 59410.535156, 119822.140625, 126201.625, 127047.148438, 128772.632812, 59911.070312, 121788.773438, 127521.796875, 130545.640625, 130645.570312, 60420.109375, 122488.039062, 129064.78125, 131856.8125, 131147.546875, 61508.890625, 123641.632812, 129653.078125, 133402.8125, 133298.625, 62822.085938, 125091.617188, 131450.578125, 134242.265625, 132676.859375, 63382.023438, 127141.789062, 133090.71875, 135306.546875, 136606.1875, 27135.890625, 42146.855469, 43478.261719, 44016.507812, 44382.800781, 14668.805664, 35516.09375, 39024.390625, 40506.328125, 41210.558594, 14608.537109, 35368.886719, 38988.730469, 40314.960938, 40933.800781, 14883.720703, 35874.441406, 39348.292969, 40816.328125, 41410.546875, 15355.085938, 36270.898438, 39530.574219, 40429.5625, 40738.382812, 15500.121094, 36425.726562, 39275.851562, 40163.164062, 40544.820312, 15579.357422, 35814.214844, 38670.695312, 39714.550781, 40012.503906, 15798.568359, 35904.628906, 38496.242188, 39493.984375, 39677.621094, 15798.568359, 35516.09375, 37780.402344, 38635.675781, 39131.765625, 15751.907227, 34934.496094, 37415.960938, 38288.960938, 38083.902344, 15500.121094, 34151.546875, 36056.339844, 36771.042969, 37187.679688, 15421.686523, 33455.304688, 35575.320312, 42524.917969, 51148.851562, 26026.839844, 61642.1875, 65725.289062, 67015.703125, 68139.476562, 29684.601562, 67546.171875, 71930.320312, 72913.703125, 74052.648438, 30821.09375, 69754.765625, 74052.648438, 75896.828125, 75762.0625, 31597.136719, 71568.351562, 76577.921875, 77693.476562, 77906.265625, 32241.814453, 72789.3125, 77693.476562, 77977.460938, 79061.148438, 33015.21875, 74570.34375, 79429.101562, 80402.007812, 80935.820312, 33507.851562, 75896.828125, 81089.640625, 82182.984375, 82821.09375, 34096.964844, 77271.351562, 82182.984375, 83550.914062, 84044.648438, 34678.949219, 78551.703125, 83387.625, 84965.148438, 85304.898438, 35164.835938, 79875.195312, 84628.101562, 85906.039062, 86166.273438, 35605.007812, 80629.921875, 85390.257812, 87581.25, 88306.3125, 36178.632812, 81867.601562, 86603.515625, 87671.234375, 89698.671875, 31227.128906, 44849.335938, 44429.019531, 43257.855469, 42909.824219, 14499.320312, 31503.814453, 34594.59375, 35634.742188, 36086.832031, 13840.830078, 29809.035156, 32636.410156, 33666.492188, 34151.546875, 13628.620117, 29157.175781, 31457.361328, 32437.912109, 32887.976562, 13499.261719, 28231.142578, 30468.935547, 31158.714844, 31227.128906, 13061.224609, 27309.580078, 29137.263672, 29746.6875, 29934.517578, 12741.389648, 26074.556641, 27807.951172, 28138.052734, 28648.164062, 12307.692383, 24960.998047, 26545.001953, 26795.060547, 26998.523438, 11627.907227, 23673.015625, 25256.511719, 25467.568359, 25467.568359, 11212.333984, 22168.341797, 23620.59375, 24237.833984, 24141.833984, 10836.4375, 20969.855469, 22214.509766, 22471.910156, 22377.623047, 10413.277344, 19728.730469, 20949.263672, 21115.142578, 28571.427734, 21519.837891, 48503.222656, 51333.46875, 51832.355469, 52405.324219, 26512.013672, 56091.148438, 58837.050781, 58999.769531, 58394.160156, 28476.083984, 59163.394531, 61288.003906, 62000.484375, 62045.566406, 29684.601562, 62408.582031, 64386.316406, 64192.578125, 63713.289062, 30556.21875, 63476.320312, 65775.953125, 66597.296875, 66286.898438, 31341.822266, 66493.507812, 68085.109375, 68743.289062, 68193.929688, 32144.650391, 67922.523438, 70503.992188, 70041.039062, 70387.679688, 33015.21875, 70156.210938, 72112.679688, 71930.320312, 72173.664062, 33350.703125, 71448.507812, 73732.71875, 73988.4375, 73605.523438, 34015.414062, 72418.671875, 75161.476562, 74635.570312, 75029.304688, 34482.757812, 74245.9375, 77131.664062, 77411.554688, 76577.921875, 35164.835938, 75762.0625, 78769.234375, 78048.78125, 78335.375], '1': [9646158.0, 22606416.0, 24376418.0, 25680250.0, 26897600.0, 6484860.5, 18990438.0, 21515430.0, 22513226.0, 24749244.0, 6508043.5, 18492100.0, 21947756.0, 22629834.0, 22351978.0, 6327090.0, 17974766.0, 21018602.0, 22723994.0, 23659206.0, 6527490.0, 17828074.0, 20505632.0, 21794480.0, 22866714.0, 6703764.5, 18244988.0, 21038844.0, 21729442.0, 22036314.0, 6606451.5, 17901120.0, 20660782.0, 21881804.0, 22818942.0, 6753503.5, 17683756.0, 20486402.0, 21838054.0, 22443836.0, 6825244.5, 17250856.0, 20090742.0, 21643328.0, 22374872.0, 6898526.5, 18229764.0, 20428928.0, 20938020.0, 21557894.0, 6766054.0, 17541756.0, 19925814.0, 21099806.0, 21707850.0, 6960068.0, 18019246.0, 20621774.0, 20164924.0, 24609838.0, 7546752.5, 20390790.0, 24054322.0, 25635048.0, 27047462.0, 8210473.5, 21643328.0, 25206154.0, 26749388.0, 27929256.0, 8517806.0, 22629834.0, 26765774.0, 27840272.0, 28699802.0, 8673372.0, 23231478.0, 26930758.0, 28605848.0, 29414722.0, 8820458.0, 24227726.0, 27611544.0, 29120640.0, 30145354.0, 8957900.0, 24805450.0, 28401300.0, 29897810.0, 30782528.0, 9199326.0, 25545118.0, 29043208.0, 30567164.0, 31379458.0, 9381048.0, 26047694.0, 29614098.0, 31111322.0, 32094026.0, 9545004.0, 26473844.0, 30187010.0, 31629344.0, 32866600.0, 9578486.0, 26716674.0, 30674468.0, 32403462.0, 33090634.0, 9732106.0, 27300978.0, 31089184.0, 32621204.0, 33651348.0, 9819598.0, 27716642.0, 31675206.0, 33090634.0, 34071224.0, 14817092.0, 38550588.0, 40404440.0, 42158892.0, 45026452.0, 9324986.0, 32891342.0, 36766340.0, 38180016.0, 40819684.0, 9437788.0, 31629344.0, 38013920.0, 38550588.0, 37109852.0, 9340935.0, 31334448.0, 36277884.0, 38516604.0, 39924460.0, 9462316.0, 30041714.0, 33991700.0, 36520480.0, 37980876.0, 9863937.0, 31402012.0, 35949532.0, 36157792.0, 35802240.0, 9397190.0, 30207882.0, 34611036.0, 36277884.0, 38047024.0, 9881785.0, 30397032.0, 33833764.0, 35802240.0, 37427756.0, 10073163.0, 29276748.0, 32891342.0, 35310344.0, 36859392.0, 10073163.0, 30083084.0, 33859984.0, 34721060.0, 35224940.0, 9837286.0, 29316036.0, 32475718.0, 34393072.0, 35310344.0, 10148033.0, 30207882.0, 34285116.0, 34887412.0, 41127080.0, 11421401.0, 37588760.0, 42322248.0, 45781348.0, 47576044.0, 12581302.0, 39779060.0, 45119448.0, 47165168.0, 49979792.0, 13008337.0, 41321564.0, 46561988.0, 49808856.0, 51451228.0, 13125576.0, 42528228.0, 47784176.0, 50852376.0, 52692260.0, 13333876.0, 43115788.0, 49752136.0, 53531548.0, 53729044.0, 13701861.0, 44072628.0, 51511888.0, 53729044.0, 55083840.0, 13911271.0, 45072904.0, 51817356.0, 54262884.0, 56217884.0, 13946797.0, 46022472.0, 53335504.0, 55503704.0, 57779148.0, 14293566.0, 46168368.0, 53400692.0, 56217884.0, 57702840.0, 14359334.0, 46962380.0, 54262884.0, 56876544.0, 58319020.0, 14540936.0, 47679884.0, 55153376.0, 58280124.0, 59028148.0, 14579755.0, 49414516.0, 55858512.0, 58948504.0, 60583316.0, 33343170.0, 55363040.0, 60541340.0, 62758916.0, 65291160.0, 23182172.0, 53140888.0, 60207624.0, 61608460.0, 63766480.0, 23582584.0, 53630116.0, 60625348.0, 62400380.0, 62939736.0, 23330722.0, 53076332.0, 60499424.0, 63488496.0, 66331984.0, 24651496.0, 53011932.0, 59836568.0, 62758916.0, 65096596.0, 25249856.0, 53696028.0, 61048904.0, 64093888.0, 64951436.0, 25047200.0, 53108588.0, 60751796.0, 63719980.0, 66382376.0, 25710474.0, 54161984.0, 59836568.0, 64093888.0, 66993100.0, 25801574.0, 54262884.0, 59108004.0, 64000000.0, 66231432.0, 26346130.0, 54431892.0, 61565056.0, 63766480.0, 64903192.0, 25816820.0, 54499792.0, 60625348.0, 64615232.0, 66635484.0, 26125574.0, 55503704.0, 62894432.0, 66788280.0, 65683788.0, 28737558.0, 62668896.0, 70849728.0, 74663632.0, 78275304.0, 31311992.0, 65291160.0, 73843384.0, 77169264.0, 79703256.0, 32000000.0, 67615168.0, 76493728.0, 79776016.0, 85222368.0, 32000000.0, 68840336.0, 77926280.0, 81945608.0, 83832424.0, 32669990.0, 69998400.0, 78982824.0, 82956960.0, 85639984.0, 32669990.0, 71958280.0, 80215424.0, 84399224.0, 86745200.0, 33115716.0, 72255792.0, 80883680.0, 86573312.0, 87967784.0, 33729284.0, 73781032.0, 82878280.0, 86146568.0, 88323448.0, 33965276.0, 73718784.0, 83035792.0, 87439624.0, 89407912.0, 34044676.0, 74282800.0, 84236504.0, 87177920.0, 89683200.0, 34447308.0, 74983984.0, 84644496.0, 88145256.0, 90895976.0, 34556288.0, 75764160.0, 85892528.0, 89683200.0, 91754984.0, 12297992.0, 29316036.0, 31067078.0, 34177836.0, 35598044.0, 9069471.0, 26570444.0, 30041714.0, 31289568.0, 33703264.0, 9183857.0, 26489894.0, 30631456.0, 30717600.0, 31022958.0, 9107282.0, 25939442.0, 30124570.0, 32596866.0, 33343170.0, 9348930.0, 25816820.0, 29434538.0, 31155692.0, 32916122.0, 9612203.0, 26700346.0, 30270670.0, 31356938.0, 32000000.0, 9520046.0, 25893322.0, 30652946.0, 32070468.0, 32965794.0, 9732106.0, 26063234.0, 29674440.0, 31813592.0, 32792594.0, 9935719.0, 25323030.0, 29795862.0, 31560800.0, 32572564.0, 9944765.0, 26393878.0, 29394932.0, 30503142.0, 31133492.0, 9908679.0, 25877986.0, 29218012.0, 30782528.0, 32023454.0, 10195395.0, 26473844.0, 29514074.0, 33573772.0, 36098044.0, 11029283.0, 30717600.0, 35540132.0, 38313944.0, 39779060.0, 12339672.0, 32768000.0, 37459844.0, 39491412.0, 41049796.0, 12537976.0, 33991700.0, 39067660.0, 40857856.0, 42569664.0, 12832583.0, 34583640.0, 39706756.0, 41795920.0, 42904092.0, 13031617.0, 35685272.0, 40516848.0, 42322248.0, 43851456.0, 13269083.0, 36038492.0, 41243548.0, 43502156.0, 44658264.0, 13565721.0, 37015532.0, 42118252.0, 43939660.0, 45306604.0, 13641965.0, 37686028.0, 42819992.0, 44567156.0, 46217208.0, 13840760.0, 38080184.0, 43073284.0, 45026452.0, 46911956.0, 13875926.0, 38755764.0, 43807488.0, 45781348.0, 47063556.0, 14000427.0, 38790176.0, 44028216.0, 46315196.0, 47731972.0, 14118053.0, 39562932.0, 44749744.0, 46761328.0, 48916588.0, 5285161.5, 9077008.0, 9269590.0, 8950560.0, 9478739.0, 2201558.75, 7040825.0, 8216650.0, 8639072.0, 8537780.0, 2173520.75, 6964506.0, 8029404.5, 8571279.0, 8167497.5, 2173520.75, 6902886.0, 7959193.5, 8511169.0, 9009623.0, 2282530.0, 6894172.0, 7982460.5, 8393443.0, 8680265.0, 2363531.5, 7086505.0, 8047151.5, 8419322.0, 8598268.0, 2380011.5, 6833785.0, 7878817.0, 8272658.5, 8451896.0, 2424386.0, 7063591.5, 7878817.0, 8118929.5, 8380562.5, 2437369.75, 7031759.5, 7722837.5, 7970810.0, 8266397.5, 2481672.25, 7013698.5, 7711932.0, 8059026.0, 8179730.5, 2472683.25, 6799751.0, 7572914.5, 7844864.5, 7936062.0, 2470446.25, 6803986.5, 7609846.5, 7918801.5, 8632244.0, 3504599.0, 11119104.0, 12893173.0, 13532108.0, 13779647.0, 4102153.25, 12720497.0, 14191425.0, 14618782.0, 14837220.0, 4360926.5, 13382887.0, 14787004.0, 15348009.0, 15522501.0, 4553641.0, 13875926.0, 15511479.0, 15941620.0, 16129953.0, 4714820.0, 14416190.0, 15837603.0, 16371721.0, 16582996.0, 4861721.0, 14908098.0, 16298433.0, 16956274.0, 17332980.0, 5064606.0, 15434762.0,

## Tea powder

In [ ]:
import json
import pandas as pd

# change the below according to the sample
specimen_file_path = "/content/tea_powder_3.bmespecimen"
label = "tea_powder"

with open(specimen_file_path, 'r') as f:
    data = json.load(f)

sensor_data = data.get('data')
specimenDataPoints = sensor_data.get('specimenDataPoints')
if specimenDataPoints:
    print("Extracted specimenDataPoints:")
    print(specimenDataPoints)
        # Separate the IDs and data
    ids = [point[0] for point in specimenDataPoints]
    data_values = [point[1:] for point in specimenDataPoints]

    # Create the DataFrame
    df = pd.DataFrame(data_values)

    # Insert the ID column at the beginning
    df.insert(0, 'id', ids)

    print("DataFrame created:")
    display(df.head())
else:
    print("'specimenDataPoints' key not found in the JSON data.")

# getting sensor values for each step in the cycles
dataset = {}
for i in range(0,10):
  filtered_list = df.loc[df[7] == i, 0].tolist()
  dataset[str(i)] = filtered_list
print(dataset)

# convert extracted values to a dataframe
min_len = min(len(v) for v in dataset.values())
for k, v in dataset.items():
    dataset[k] = v[:min_len]
df = pd.DataFrame(dataset)
# df.head()

# Add data label
df['label'] = label
df.head()

# Save the data
df.to_csv(f"{label}.csv", index = False)

Extracted specimenDataPoints:

,id,0,1,2,3,4,5,6,7,8
0,14851,1.177553e+05,33.669094,1004.919922,31.940468,0,1763832028,0,0,1486
1,14852,9.246050e+06,33.536465,1004.979370,31.645233,280,1763832029,0,1,1486
2,14853,7.260802e+06,33.712456,1004.983521,30.341644,1680,1763832030,0,2,1486
3,14854,4.591928e+06,34.095039,1004.983704,27.611353,5880,1763832034,0,3,1486
4,14855,3.580420e+05,34.671474,1004.928284,27.351219,6580,1763832035,0,4,1486

{'0': [117755.289062, 232780.171875, 248543.6875, 252216.75, 251844.5625, 112775.328125, 213957.375, 227808.671875, 235510.578125, 236489.609375, 110083.851562, 209621.296875, 225699.796875, 228418.46875, 231360.140625, 109308.28125, 206576.5625, 223045.09375, 228265.71875, 231674.203125, 109168.445312, 208087.78125, 221309.703125, 225849.140625, 230267.59375, 108543.5625, 207203.5625, 221597.0625, 225401.71875, 229339.3125, 108268.132812, 207581.59375, 220167.703125, 223923.03125, 226749.328125, 109168.445312, 206576.5625, 219318.90625, 225104.421875, 231046.9375, 109028.960938, 206326.8125, 219601.109375, 227353.46875, 227051.0, 109098.65625, 206576.5625, 221741.015625, 225550.65625, 229185.3125, 108405.671875, 205457.46875, 218756.671875, 228571.421875, 231831.5625, 109518.71875, 206202.171875, 219884.046875, 225401.71875, 115523.46875, 247642.078125, 259503.296875, 264326.28125, 262093.671875, 117918.007812, 224659.9375, 239308.25, 242023.15625, 244100.125, 115994.5625, 218896.96875, 235186.03125, 240150.09375, 240658.046875, 115133.796875, 217779.671875, 232780.171875, 236982.1875, 239476.140625, 113601.0625, 217363.609375, 229493.5, 236817.765625, 237476.8125, 114209.234375, 218057.921875, 230578.703125, 235510.578125, 238973.15625, 113828.367188, 216673.71875, 231360.140625, 234217.75, 238973.15625, 113752.5, 217363.609375, 231360.140625, 235186.03125, 237311.703125, 114285.710938, 217640.8125, 231831.5625, 234700.890625, 237311.703125, 113450.03125, 218476.640625, 230578.703125, 235836.015625, 236982.1875, 113299.40625, 218197.3125, 231203.4375, 237146.828125, 238973.15625, 114438.984375, 218616.5625, 231831.5625, 236653.578125, 193025.453125, 282015.96875, 291157.25, 290167.1875, 287721.28125, 178459.390625, 257934.515625, 266181.4375, 267852.46875, 269544.625, 174446.34375, 251844.5625, 262295.09375, 265147.59375, 267223.375, 170951.59375, 254663.015625, 260294.859375, 264531.125, 265766.9375, 171294.75, 254283.578125, 263510.03125, 265766.9375, 265766.9375, 171466.84375, 254283.578125, 262496.78125, 264531.125, 266181.4375, 171294.75, 254283.578125, 264941.78125, 265766.9375, 266389.1875, 172332.546875, 254473.15625, 265147.59375, 265974.03125, 267432.75, 171639.296875, 255425.296875, 264941.78125, 267014.34375, 267642.4375, 171466.84375, 257351.09375, 264736.3125, 269119.59375, 268484.53125, 172158.703125, 257739.75, 267014.34375, 267014.34375, 268907.5625, 172158.703125, 258520.578125, 264531.125, 268907.5625, 140312.421875, 257157.203125, 269757.625, 269971.0, 267642.4375, 132060.875, 231203.4375, 244449.75, 250183.234375, 252216.75, 127808.289062, 226148.40625, 239812.640625, 246213.03125, 246925.484375, 127236.578125, 225252.96875, 239476.140625, 242884.25, 244976.078125, 126388.546875, 224512.171875, 237807.703125, 243925.671875, 245504.671875, 126108.375, 222753.96875, 236817.765625, 240319.171875, 244449.75, 126295.015625, 224807.90625, 237146.828125, 241851.671875, 243751.484375, 125922.28125, 223336.96875, 235673.1875, 241509.4375, 244624.9375, 126295.015625, 224070.015625, 236817.765625, 240319.171875, 244800.375, 125459.445312, 224217.203125, 235024.09375, 241851.671875, 243057.203125, 125922.28125, 225252.96875, 237146.828125, 241168.15625, 245858.34375, 125183.375, 225252.96875, 237476.8125, 242884.25, 72665.34375, 158858.203125, 169088.5, 170951.59375, 173383.0, 82740.789062, 156527.0625, 163735.203125, 166612.4375, 167101.828125, 81867.601562, 153155.84375, 161565.15625, 164683.171875, 165481.578125, 81399.046875, 152199.765625, 161718.25, 163735.203125, 165321.28125, 81321.476562, 153431.21875, 160350.765625, 163421.640625, 164683.171875, 81946.226562, 153018.53125, 160350.765625, 162488.09375, 165321.28125, 82024.992188, 151793.65625, 161565.15625, 163421.640625, 164842.234375, 82421.117188, 153707.59375, 160350.765625, 164524.421875, 165321.28125, 82740.789062, 154682.78125, 162488.09375, 165161.296875, 166449.9375, 82982.171875, 154682.78125, 162953.53125, 165321.28125, 166938.375, 82982.171875, 155528.546875, 164049.984375, 166287.75, 167758.84375, 83306.21875, 155812.53125, 165001.609375, 166938.375, 168921.140625, 56054.300781, 121183.429688, 127521.796875, 128869.875, 128675.546875, 62226.542969, 117836.59375, 123195.382812, 124362.398438, 124000.96875, 61642.1875, 115758.53125, 120840.21875, 121269.539062, 121615.203125, 61288.003906, 114823.953125, 119486.578125, 121442.125, 121528.601562, 61508.890625, 113601.0625, 117512.046875, 121097.445312, 120498.9375, 61820.816406, 112924.570312, 117512.046875, 119654.125, 120159.585938, 62000.484375, 112552.210938, 119319.507812, 119152.898438, 119822.140625, 62000.484375, 112849.898438, 117755.289062, 119152.898438, 120584.078125, 62317.429688, 112478.03125, 118738.40625, 120244.25, 119822.140625, 62683.644531, 113752.5, 118986.75, 120584.078125, 120584.078125, 62822.085938, 113676.734375, 119990.625, 120840.21875, 121355.773438, 62914.722656, 115758.53125, 120244.25, 122312.46875, 32315.072266, 75360.609375, 78914.921875, 79281.507812, 79651.523438, 33934.253906, 71329.0625, 75095.335938, 75829.382812, 75762.0625, 33220.867188, 70041.039062, 73289.4375, 73924.34375, 74310.59375, 33040.785156, 68965.515625, 72295.960938, 72851.453125, 73796.484375, 32736.572266, 68248.46875, 71448.507812, 72480.179688, 72851.453125, 32586.558594, 67706.953125, 71388.734375, 72480.179688, 72603.515625, 32536.857422, 67492.75, 70737.773438, 72234.765625, 72173.664062, 32661.392578, 67332.984375, 71091.367188, 71748.882812, 72173.664062, 32711.474609, 67015.703125, 71210.015625, 71628.429688, 71748.882812, 32786.886719, 67279.898438, 71210.015625, 71688.601562, 71688.601562, 32761.708984, 67546.171875, 70973.109375, 72051.789062, 72789.3125, 32862.644531, 67546.171875, 71329.0625, 72051.789062, 31503.814453, 72112.679688, 74831.921875, 74505.242188, 74440.242188, 33853.476562, 68139.476562, 69640.914062, 69926.25, 69527.429688, 33066.390625, 66286.898438, 68085.109375, 67976.632812, 68357.8125, 32761.708984, 64777.328125, 66493.507812, 66390.039062, 66753.585938, 32661.392578, 63856.324219, 66338.429688, 65725.289062, 65928.40625, 32686.414062, 63665.753906, 65322.785156, 66338.429688, 65826.6875, 32413.269531, 63334.984375, 64728.191406, 66235.445312, 66235.445312, 32512.064453, 63334.984375, 65928.40625, 66030.4375, 65725.289062, 32837.351562, 63288.011719, 65523.417969, 66390.039062, 66030.4375, 32636.410156, 63523.574219, 65123.378906, 66184.078125, 66235.445312, 32989.691406, 64000.0, 65877.507812, 66441.734375, 66286.898438, 32964.203125, 63194.273438, 66235.445312, 66649.3125, 66132.78125], '1': [9246050.0, 25862668.0, 28254366.0, 28851420.0, 28775412.0, 8799141.0, 22329132.0, 25075952.0, 26001190.0, 26330254.0, 8342159.0, 21643328.0, 24376418.0, 25220704.0, 25411400.0, 8235235.0, 21284832.0, 23608070.0, 24582146.0, 25090352.0, 8112899.0, 20938020.0, 23256210.0, 24376418.0, 24947088.0, 8173609.5, 20998398.0, 22890674.0, 24376418.0, 25047200.0, 8112899.0, 20877986.0, 23011236.0, 24308606.0, 24947088.0, 8143141.0, 20917970.0, 23305832.0, 24444610.0, 24791376.0, 8198148.5, 20897960.0, 22962860.0, 24322138.0, 24947088.0, 8216650.0, 20958106.0, 23256210.0, 24362826.0, 25590004.0, 8143141.0, 21284832.0, 23355666.0, 24485708.0, 24947088.0, 8198148.5, 20917970.0, 23256210.0, 24665412.0, 11906977.0, 41478480.0, 45026452.0, 45685604.0, 45306604.0, 12459316.0, 35453612.0, 38755764.0, 39779060.0, 40329848.0, 11932993.0, 33833764.0, 36984200.0, 38448812.0, 39172744.0, 11566537.0, 33547990.0, 36398780.0, 38893768.0, 38415004.0, 11385685.0, 33216422.0, 36398780.0, 37556448.0, 38246864.0, 11303208.0, 32743442.0, 36157792.0, 37299944.0, 38280372.0, 11279862.0, 32621204.0, 36368480.0, 37236364.0, 37621124.0, 11187436.0, 32841894.0, 36217740.0, 37491992.0, 37783800.0, 11268226.0, 32866600.0, 36068244.0, 37046920.0, 38080184.0, 11233459.0, 32866600.0, 36157792.0, 37718560.0, 37914956.0, 11245024.0, 32792594.0, 36008792.0, 37395720.0, 37849264.0, 11198906.0, 32718922.0, 36642996.0, 37588760.0, 30354794.0, 57626732.0, 60415764.0, 61219992.0, 60457564.0, 27472648.0, 50822800.0, 51451228.0, 53466040.0, 53861516.0, 26094366.0, 46661444.0, 51481540.0, 52313708.0, 53531548.0, 25740770.0, 46962380.0, 50911632.0, 51940560.0, 52979788.0, 25545118.0, 47114308.0, 50911632.0, 52251148.0, 53335504.0, 25620016.0, 47318412.0, 51270096.0, 52597112.0, 53630116.0, 25500390.0, 47114308.0, 51572692.0, 53140888.0, 53828336.0, 25500390.0, 47369716.0, 51786644.0, 53140888.0, 53498776.0, 25381874.0, 49219676.0, 51694736.0, 53466040.0, 54195576.0, 25470656.0, 49386588.0, 52188732.0, 53729044.0, 54364164.0, 25620016.0, 48725652.0, 52313708.0, 53994644.0, 54499792.0, 25605000.0, 49026368.0, 52851612.0, 54229208.0, 13540496.0, 34748676.0, 37427756.0, 38080184.0, 37686028.0, 12174624.0, 29514074.0, 32164908.0, 33140834.0, 33522250.0, 11421401.0, 28456796.0, 31111322.0, 32212338.0, 32524070.0, 11187436.0, 28181466.0, 30291658.0, 31606462.0, 32141246.0, 11198906.0, 27559294.0, 30375898.0, 31424598.0, 31883240.0, 11198906.0, 27629006.0, 30249712.0, 31022958.0, 31859990.0, 11119104.0, 27541920.0, 30249712.0, 31022958.0, 31379458.0, 11007054.0, 27929256.0, 30166168.0, 30869524.0, 31200190.0, 11130435.0, 27646488.0, 30062386.0, 30913208.0, 31560800.0, 11074011.0, 27751852.0, 30083084.0, 31045002.0, 31515268.0, 11096512.0, 27629006.0, 30103812.0, 30913208.0, 31859990.0, 10984915.0, 27663994.0, 30291658.0, 31022958.0, 4360926.5, 15964921.0, 17755622.0, 18063948.0, 18229764.0, 5357750.0, 15198516.0, 16495344.0, 16851632.0, 16956274.0, 5305699.5, 14737126.0, 16165762.0, 16482897.0, 16761125.0, 5310859.0, 14757037.0, 15929995.0, 16371721.0, 16359461.0, 5316028.5, 14618782.0, 15976597.0, 16347219.0, 16433300.0, 5336808.0, 14609006.0, 15906796.0, 16201731.0, 16433300.0, 5331598.0, 14857402.0, 16035234.0, 16310602.0, 16608211.0, 5400132.0, 14817092.0, 16153808.0, 16433300.0, 16722633.0, 5459513.5, 14918279.0, 16094303.0, 16658871.0, 16890722.0, 5497986.5, 15051906.0, 16359461.0, 16851632.0, 17156020.0, 5520215.5, 15304998.0, 16532795.0, 16956274.0, 17319238.0, 5542625.0, 15522501.0, 16646177.0, 17115696.0, 17555854.0, 2532303.0, 8841878.0, 9511756.0, 9680355.0, 9697544.0, 3187548.75, 8425816.0, 8914037.0, 8950560.0, 8899511.0, 3098922.0, 8118929.5, 8763841.0, 8827586.0, 8735804.0, 2976744.25, 7988298.5, 8412837.0, 8584752.0, 8639072.0, 3069314.25, 7907336.0, 8478137.0, 8571279.0, 8578010.0, 3072768.25, 7873138.0, 8445361.0, 8551148.0, 8598268.0, 3139900.25, 7924546.5, 8425816.0, 8611827.0, 8618622.0, 3127314.25, 7964997.5, 8471562.0, 8632244.0, 8707946.0, 3193139.75, 8100865.5, 8639072.0, 8714894.0, 8827586.0, 3240506.25, 8124969.0, 8659619.0, 8914037.0, 8841878.0, 3281394.0, 8260146.0, 8770878.0, 9017061.0, 8979995.0, 3293266.25, 8361316.5, 8892266.0, 9069471.0, 1351369.125, 5520215.5, 5870297.5, 5870297.5, 5851428.5, 1567247.0, 4896593.0, 5244558.5, 5290281.0, 5300550.0, 1477100.625, 4780858.0, 5078735.5, 5170085.0, 5160315.0, 1448885.75, 4619114.5, 4976913.5, 5069307.0, 5107232.0, 1447349.875, 4599663.0, 4936426.5, 5008866.0, 4986001.0, 1439718.75, 4557441.0, 4931968.5, 5018070.5, 4936426.5, 1439718.75, 4595792.5, 4914217.0, 4990557.5, 5018070.5, 1438202.25, 4588070.5, 4892206.5, 5055230.0, 5041231.0, 1448885.75, 4626941.5, 4986001.0, 5064606.0, 5036581.5, 1456614.5, 4634795.0, 5036581.5, 5145728.5, 5102460.5, 1473911.5, 4714820.0, 5102460.5, 5209539.0, 5150581.5, 1480303.625, 4731158.0, 5145728.5, 5179892.5, 1191043.875, 4364411.5, 4630865.0, 4557441.0, 4460659.0, 1368984.0, 3900023.75, 4080697.5, 4020613.5, 3950807.75, 1316195.375, 3768169.25, 3894461.5, 3900023.75, 3826249.5, 1306122.5, 3662047.5, 3786457.25, 3752634.0, 3765571.25, 1307373.125, 3611196.75, 3762976.5, 3747484.0, 3732118.5, 1321290.375, 3580419.5, 3760385.5, 3752634.0, 3727024.5, 1321290.375, 3637655.5, 3727024.5, 3729569.75, 3699255.0, 1329007.125, 3573391.5, 3773376.25, 3861418.75, 3744914.25, 1332899.5, 3649810.75, 3768169.25, 3791715.0, 3783833.75, 1351369.125, 3696751.0, 3869626.75, 3875118.25, 3866887.0, 1377269.625, 3752634.0, 3897240.75, 3902810.75, 3864151.0, 1399863.25, 3783833.75, 4038452.0, 3982498.75, 3894461.5], '2': [7260802.0, 19156972.0, 20390790.0, 20409842.0, 20428928.0, 6562788.0, 15929995.0, 17541756.0, 18063948.0, 18306146.0, 6162874.0, 15380427.0, 16709842.0, 17278144.0, 17485592.0, 6030180.5, 14877639.0, 16371721.0, 16890722.0, 17102296.0, 5934082.0, 14807049.0, 16420947.0, 16595594.0, 16748275.0, 5863994.5, 14589492.0, 16000000.0, 16396297.0, 16735444.0, 5845166.0, 14599243.0, 15837603.0, 16310602.0, 16646177.0, 5820248.5, 14502324.0, 15780400.0, 16298433.0, 16608211.0, 5814052.5, 14511957.0, 15769009.0, 16298433.0, 16507809.0, 5801699.5, 14454345.0, 15803231.0, 16262035.0, 16520292.0, 5807869.5, 14425710.0, 15734934.0, 16433300.0, 16916882.0, 5838916.5, 14502324.0, 15757634.0, 16310602.0, 8185860.5, 24268098.0, 25680250.0, 25515282.0, 25075952.0, 7777830.5, 19603948.0, 20998398.0, 21368112.0, 21452046.0, 7265632.0, 18570700.0, 19889530.0, 20127764.0, 20621774.0, 7100325.0, 18063948.0, 19309370.0, 19727874.0, 19925814.0, 6929160.5, 17755622.0, 18859280.0, 19446884.0, 19533830.0, 6855230.0, 17499600.0, 18794380.0, 19258302.0, 19190630.0, 6842347.0, 17388166.0, 18634064.0, 19023512.0, 19275294.0, 6808227.5, 17278144.0, 18460846.0, 19156972.0, 19241338.0, 6782860.5, 17346744.0, 18523460.0, 19023512.0, 19207502.0, 6770248.0, 17402018.0, 18539180.0, 19040092.0, 19326452.0, 6799751.0, 17388166.0, 18492100.0, 19006960.0, 19224406.0, 6766054.0, 17415892.0, 18665908.0, 19309370.0, 21751078.0, 37395720.0, 38584632.0, 38313944.0, 38280372.0, 19292316.0, 31976580.0, 33267006.0, 33651348.0, 34097816.0, 18414162.0, 31289568.0, 32694438.0, 33165992.0, 33677288.0, 18063948.0, 31000946.0, 32403462.0, 32743442.0, 33343170.0, 18034122.0, 30739212.0, 32621204.0, 33241694.0, 33241694.0, 17901120.0, 30760854.0, 32451596.0, 33015618.0, 33065590.0, 17770066.0, 31067078.0, 32694438.0, 33216422.0, 33317742.0, 17799022.0, 31222486.0, 33090634.0, 33547990.0, 33625448.0, 17945236.0, 31379458.0, 33140834.0, 33267006.0, 33755344.0, 17959990.0, 31629344.0, 33090634.0, 33859984.0, 33859984.0, 17945236.0, 31790444.0, 33625448.0, 33912548.0, 33781444.0, 18078896.0, 32000000.0, 33267006.0, 34018168.0, 9663226.0, 22536452.0, 23455978.0, 24376418.0, 24120722.0, 8598268.0, 18826774.0, 20146326.0, 20505632.0, 20758948.0, 8070936.0, 17901120.0, 19343566.0, 19745706.0, 20035464.0, 7856149.5, 17429788.0, 18859280.0, 19326452.0, 19533830.0, 7822392.0, 17075560.0, 18398652.0, 19140186.0, 19326452.0, 7728302.0, 17035612.0, 18414162.0, 18941040.0, 19429588.0, 7679400.0, 17169504.0, 18778224.0, 19040092.0, 19073342.0, 7641791.0, 17319238.0, 18429696.0, 19023512.0, 19123432.0, 7701057.5, 16956274.0, 18383170.0, 18859280.0, 19190630.0, 7755739.5, 17183010.0, 18586500.0, 18794380.0, 19106706.0, 7722837.5, 17048908.0, 18492100.0, 19023512.0, 19292316.0, 7744741.0, 17102296.0, 18460846.0, 18891900.0, 2488456.75, 6642611.0, 6986780.5, 7100325.0, 7123478.5, 2788291.25, 6226107.0, 6504168.5, 6598469.5, 6642611.0, 2754539.25, 6050221.5, 6327090.0, 6473330.5, 6431403.5, 2710787.5, 5908402.5, 6305176.0, 6356547.0, 6378820.5, 2713481.25, 6013580.5, 6341784.5, 6408762.0, 6450393.5, 2732488.25, 6010271.5, 6283413.0, 6371378.5, 6477169.5, 2754539.25, 6117998.5, 6405004.0, 6484860.5, 6435192.5, 2768502.75, 6190818.0, 6481012.5, 6570684.0, 6638573.5, 2817056.5, 6301538.5, 6614453.0, 6606451.5, 6646653.0, 2840499.25, 6360248.5, 6650700.0, 6749330.5, 6766054.0, 2882477.25, 6420062.5, 6761865.5, 6850930.5, 6808227.5, 2900849.75, 6554911.0, 6876810.0, 6937963.0, 6951209.0, 1286432.125, 2867343.25, 2976744.25, 2979992.75, 2928852.25, 1429169.625, 2727030.75, 2811256.0, 2796859.0, 2757320.75, 1387064.0, 2668404.0, 2732488.25, 2737968.0, 2724310.0, 1374496.625, 2642580.75, 2708099.25, 2713481.25, 2713481.25, 1370358.0, 2665799.0, 2718884.75, 2708099.25, 2748993.25, 1391304.375, 2673629.25, 2808364.75, 2748993.25, 2768502.75, 1433671.625, 2710787.5, 2782608.75, 2825802.0, 2811256.0, 1436688.875, 2740716.0, 2825802.0, 2861334.25, 2870357.5, 1467574.375, 2819965.5, 2903934.75, 2928852.25, 2928852.25, 1519287.875, 2843457.25, 2973502.75, 2989781.0, 3077963.5, 1556526.75, 2928852.25, 3138096.25, 3138096.25, 3143515.0, 1571757.5, 2976744.25, 3196878.0, 3187548.75, 526613.5, 1281602.0, 1280400.125, 1247639.375, 1220864.375, 527427.25, 1102557.25, 1107925.375, 1093725.0, 1079884.0, 502576.6875, 1047570.3125, 1062240.625, 1054040.125, 1045164.5625, 495284.15625, 1026309.1875, 1053227.0, 1040386.0625, 1027854.4375, 492071.125, 1023232.5625, 1038013.1875, 1036437.25, 1036437.25, 495643.75, 1029404.375, 1043566.875, 1050795.25, 1034082.3125, 498903.78125, 1038013.1875, 1045164.5625, 1046767.1875, 1043566.875, 500366.46875, 1054854.5, 1077327.75, 1071409.875, 1063067.75, 505928.84375, 1070569.75, 1089361.75, 1083311.25, 1081594.875, 514702.1875, 1088493.25, 1116989.375, 1120656.625, 1106130.125, 522582.28125, 1109726.375, 1135569.75, 1135569.75, 1139360.25, 531948.0625, 1136515.0, 1163636.375, 1158698.75, 564498.375, 1362155.0, 1380053.875, 1370358.0, 1330302.0, 589352.5, 1254517.625, 1241964.875, 1224148.25, 1194169.125, 571588.0625, 1196261.625, 1210044.375, 1168616.25, 1163636.375, 564031.9375, 1176673.375, 1185871.5, 1166619.25, 1185871.5, 566371.6875, 1163636.375, 1212193.0, 1164629.0, 1152828.625, 576901.4375, 1183815.0, 1186902.375, 1175660.125, 1182789.5, 578858.125, 1197310.75, 1203643.875, 1191043.875, 1177688.375, 595002.875, 1216513.25, 1228554.25, 1206835.625, 1196261.625, 599180.8125, 1243095.625, 1227449.75, 1226347.25, 1244228.375, 607715.125, 1261472.125, 1276808.0, 1263807.5, 1259145.375, 618731.125, 1287645.375, 1297434.25, 1288860.875, 1288860.875, 630736.0625, 1321290.375, 1332899.5, 1320012.875], '3': [4591928.5, 9637647.0, 9926689.0, 9714794.0, 9663226.0, 3965150.0, 7988298.5, 8406362.0, 8484723.0, 8557848.0, 3739785.5, 7505268.0, 7907336.0, 7959193.5, 8011736.0, 3578073.75, 7280160.0, 7663236.5, 7772296.0, 7755739.5, 3522683.25, 7068162.0, 7525953.0, 7572914.5, 7615152.0, 3466779.5, 7004703.0, 7403524.5, 7489828.5, 7500114.5, 3466779.5, 7013698.5, 7319187.0, 7368563.0, 7484696.0, 3436241.5, 6942373.0, 7275311.0, 7484696.0, 7373537.5, 3466779.5, 6929160.5, 7428701.0, 7343792.0, 7418610.0, 3475604.5, 6885480.0, 7236749.0, 7368563.0, 7388500.5, 3440571.25, 6885480.0, 7236749.0, 7418610.0, 7428701.0, 3414756.25, 6894172.0, 7241547.0, 4282279.0, 8598268.0, 8517806.0, 8323088.5, 8088867.0, 3739785.5, 6833785.0, 7027235.5, 6991252.5, 6982314.0, 3460190.0, 6408762.0, 6562788.0, 6558847.0, 6539213.5, 3329404.5, 6138628.5, 6341784.5, 6316114.0, 6416291.5, 3242430.25, 6033511.5, 6197844.0, 6247474.0, 6169836.0, 3213809.25, 5876614.0, 6094104.5, 6097506.5, 6131736.5, 3172734.25, 5783268.5, 6013580.5, 6100912.5, 6117998.5, 3183832.0, 5734686.5, 6053574.5, 6148996.0, 6148996.0, 3141706.5, 5764954.5, 6050221.5, 6121427.0, 6060292.0, 3127314.25, 5789399.5, 6033511.5, 6087312.0, 6121427.0, 3134494.0, 5807869.5, 6094104.5, 6087312.0, 6145536.5, 3109508.5, 5801699.5, 6033511.5, 6097506.5, 14081650.0, 20183554.0, 20582914.0, 20202220.0, 19998780.0, 11919971.0, 17415892.0, 17698082.0, 17959990.0, 17945236.0, 11421401.0, 16799794.0, 17250856.0, 17360530.0, 17741202.0, 11268226.0, 16582996.0, 17183010.0, 17584116.0, 17415892.0, 11153165.0, 16799794.0, 17169504.0, 17443706.0, 17278144.0, 11074011.0, 16722633.0, 17278144.0, 17485592.0, 17499600.0, 11074011.0, 16916882.0, 17457646.0, 17555854.0, 17402018.0, 11029283.0, 16969446.0, 17457646.0, 17499600.0, 17698082.0, 11164566.0, 17115696.0, 17569974.0, 17712432.0, 17683756.0, 11198906.0, 17196536.0, 17842636.0, 17726806.0, 17813536.0, 11245024.0, 17443706.0, 17784532.0, 17813536.0, 17886462.0, 11210400.0, 17183010.0, 17813536.0, 17945236.0, 5616729.5, 10017732.0, 10185887.0, 10063882.0, 9953827.0, 4857397.0, 8445361.0, 8666490.0, 8728823.0, 8652759.0, 4523467.5, 7959193.5, 8316751.5, 8291498.0, 8445361.0, 4417363.0, 7684803.0, 7959193.5, 8118929.5, 82

## Combine all of the above files

In [ ]:
df_air = pd.read_csv("/content/air.csv")
df_fennel_seed= pd.read_csv("/content/fennel_seeds.csv")
df_tea_powder= pd.read_csv("/content/tea_powder.csv")
df_combined = pd.concat([df_air, df_fennel_seed, df_tea_powder], ignore_index=True)
print("Combined DataFrame:")
display(df_combined.head())
df_combined.to_csv("df_combined.csv", index = False)

Combined DataFrame:

,0,1,2,3,4,5,6,7,8,9,label
0,10145.846680,1.635783e+05,166938.375,1.646832e+05,34427.113281,35486.554688,36488.027344,16507.609375,28362.507812,39384.617188,air
1,50723.203125,1.656623e+06,1605015.625,1.539850e+06,216811.343750,210526.312500,207203.562500,54479.675781,67760.718750,78696.585938,air
2,88123.921875,3.561739e+06,3427615.000,3.232834e+06,409436.218750,395443.125000,386050.906250,84377.062500,99090.382812,109308.281250,air
3,118408.882812,5.342028e+06,5121600.500,4.731158e+06,568730.937500,544680.875000,526613.500000,109028.960938,123552.125000,133194.593750,air
4,141592.921875,7.222394e+06,6816725.500,6.312464e+06,702814.000000,674349.687500,643216.062500,126952.640625,144591.921875,154682.781250,air